# -*- coding: utf-8 -*-
"""Meeting Schelu... Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDyFyOzsrZFgJ3azqQ4FIJM73WZJd_Af
"""

# Meeting Minutes Generator

import pandas as pd
from datetime import datetime
from IPython.display import display   # Needed for Colab/Jupyter