# -*- coding: utf-8 -*-
"""Product Review code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6vuE1l7WDvHIVQ1UY79nw-HMB-jruoc
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

#load sentiment analysis model
sentiment=pipeline("sentiment-analysis")
#sample product review (you can change only this text later)
review=""" the laptop starts quickly and works smoothly for daily tasks.the screen quality is clear and good for watching videos. Battery backup is average and needs charging
often. The fan makes nosie when many apps are running overall, it is a good laptop for students but not for gaming."""
#split review into sentence
sentences=review.split(".")
pros=[]
cons=[]
for s in sentences:
  s=s.strip()
  if s=="":
    continue
  result=sentiment(s)[0]
  if result["label"]=="POSITIVE":
    pros.append(s)
  elif result['label']=="NEGATIVE":
    cons.append(s)
#take only 2 pros and 2cons
pros=pros[:2]
cons=cons[:2]

# Pad shorter list to match length, ensuring both have at most 2 items
max_len = max(len(pros), len(cons))
if max_len < 2:
    max_len = 2 # Ensure we pad to 2 if both are shorter

while len(pros) < max_len:
    pros.append(None)
while len(cons) < max_len:
    cons.append(None)

#create table
df=pd.DataFrame({
    "pros":pros,
    "cons":cons
})
df