# -*- coding: utf-8 -*-
"""Text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TacAC8e37u1jg2JX4Qh3l8AivmWL_py_
"""

from transformers import pipeline
#Load text generatin model(GenAI)
generator=pipeline(
    "text-generation",
    model="gpt2"
)
#input prompt
prompt="how music heals a soul"
#generate text
result=generator(prompt,max_length=100,num_return_sequences=1)
print ("AI generated text:")
print(result[0]['generated_text'])

"""# Task
Generate a summary table for the prompt: "Google was founded in 1998 by Larry Page and Sergey Brin. The company's mission is to organize the world's information and make it universally accessible and useful. Google offers a wide range of products and services, including search engine, online advertising, cloud computing, software, and hardware." by implementing structured output generation using a suitable `transformers` model and displaying the result as a Pandas table.

## Research Table Generation Approaches

### Subtask:
Investigate available models and techniques within the Hugging Face `transformers` library that can generate structured data or tabular information from a text prompt. This will involve looking into sequence-to-sequence models or models specifically trained for structured output tasks that can produce text parsable as a table.

### Researching Models for Structured Output Generation on Hugging Face

To identify suitable models for generating structured data (like tables, CSV, or JSON) from text prompts using the Hugging Face `transformers` library, follow these steps:

1.  **Navigate to the Hugging Face Model Hub**: Go to [huggingface.co/models](https://huggingface.co/models).

2.  **Use Search Filters**: In the search bar or filters section, consider the following search terms and filters:
    *   **Tasks**: Look for tasks such as `text-to-text-generation`, `sequence-to-sequence`, `information-extraction`, `table-question-answering` (though this is often for extracting from existing tables, some models might generate them), or custom tasks related to structured data.
    *   **Keywords**: Try searching for terms like `table generation`, `structured output`, `JSON generation`, `CSV generation`, `text2table`, `data extraction`, or `knowledge graph generation`.

3.  **Evaluate Model Descriptions**: Once you find potential models, click on them to read their detailed descriptions. Pay attention to:
    *   **Input/Output Format**: Does the model explicitly state it can take a text prompt and output structured data (e.g., in JSON, CSV, or a parsable text format)?
    *   **Example Usage**: Many model cards include `transformers` pipeline examples. Look for those demonstrating structured output generation.
    *   **Training Data**: Understand what kind of data the model was trained on, as this indicates its strengths and limitations.
    *   **Documentation**: Prioritize models with clear documentation and community support.

4.  **Prioritize Models**: Favor models that are well-documented, actively maintained, and have clear examples of structured output generation. Specific architectures like **encoder-decoder models (e.g., T5, BART)** are often used for text-to-text generation tasks that can be adapted for structured output by fine-tuning with appropriate datasets and output formats.

This manual investigation is crucial to understanding the landscape of available models for this specific and complex task.

## Implement Structured Output Generation

### Subtask:
Generate structured text from the input prompt using a suitable `transformers` model, aiming for an output format that can be easily parsed into a table.

**Reasoning**:
The subtask requires generating structured text using a `text2text-generation` model. I will load the `google/flan-t5-small` model and define a prompt to extract information in a key-value pair format.
"""

from transformers import pipeline

# Load a text2text-generation model
generator_structured = pipeline(
    "text2text-generation",
    model="google/flan-t5-small"
)

# Define the input prompt for structured output
prompt_structured = "Extract the company name, founding year, founders, mission, and products/services from the following text and present them as key-value pairs separated by semicolons: 'Google was founded in 1998 by Larry Page and Sergey Brin. The company's mission is to organize the world's information and make it universally accessible and useful. Google offers a wide range of products and services, including search engine, online advertising, cloud computing, software, and hardware.'"

# Generate text with structured output
result_structured = generator_structured(prompt_structured, max_new_tokens=200)

# Print the raw generated text
print("AI generated structured text:")
print(result_structured[0]['generated_text'])

"""**Reasoning**:
The previous attempt with `flan-t5-small` failed to extract structured information, merely echoing the input text. I will modify the prompt to follow a more explicit 'Question: [Q] Text: [T] Answer: [A]' format, which is common for instruction-tuned models like Flan-T5 and should better guide the model to perform the requested extraction and formatting.


"""

from transformers import pipeline

# Load a text2text-generation model
generator_structured = pipeline(
    "text2text-generation",
    model="google/flan-t5-small"
)

# Define the input prompt for structured output
prompt_structured = (
    "Question: Extract the company name, founding year, founders, mission, and products/services from the text and present them as key-value pairs separated by semicolons. "
    "Text: 'Google was founded in 1998 by Larry Page and Sergey Brin. The company's mission is to organize the world's information and make it universally accessible and useful. Google offers a wide range of products and services, including search engine, online advertising, cloud computing, software, and hardware.' "
    "Answer:"
)

# Generate text with structured output
result_structured = generator_structured(prompt_structured, max_new_tokens=200)

# Print the raw generated text
print("AI generated structured text:")
print(result_structured[0]['generated_text'])

"""**Reasoning**:
The model is still not providing the desired structured output despite the 'Question: Text: Answer:' format. I will try providing a few-shot example within the prompt to explicitly demonstrate the expected key-value pair format, which often significantly improves instruction following for text-to-text generation models like Flan-T5.


"""

from transformers import pipeline

# Load a text2text-generation model
generator_structured = pipeline(
    "text2text-generation",
    model="google/flan-t5-small"
)

# Define the input prompt for structured output with a few-shot example
prompt_structured = (
    "Question: Extract the company name, founding year, founders, mission, and products/services from the text and present them as key-value pairs separated by semicolons. "
    "Example Text: 'Apple was founded in 1976 by Steve Jobs and Steve Wozniak. Its mission is to design, develop, and sell consumer electronics, computer software, and online services. Apple offers products like iPhone, Mac, Apple Watch, and services like Apple Music, iCloud.' "
    "Example Answer: Company Name: Apple; Founding Year: 1976; Founders: Steve Jobs, Steve Wozniak; Mission: design, develop, and sell consumer electronics, computer software, and online services; Products/Services: iPhone, Mac, Apple Watch, Apple Music, iCloud. "
    "Text: 'Google was founded in 1998 by Larry Page and Sergey Brin. The company's mission is to organize the world's information and make it universally accessible and useful. Google offers a wide range of products and services, including search engine, online advertising, cloud computing, software, and hardware.' "
    "Answer:"
)

# Generate text with structured output
result_structured = generator_structured(prompt_structured, max_new_tokens=200)

# Print the raw generated text
print("AI generated structured text:")
print(result_structured[0]['generated_text'])

"""**Reasoning**:
The `flan-t5-small` model appears to be insufficient for generating the detailed structured output even with few-shot prompting, as it consistently outputs only 'Google'. I will switch to a larger and more capable model, `google/flan-t5-base`, which has more parameters and is generally better at instruction following and generating complex, structured responses. I will also make sure to assign a new `cell_id` for the code block as this is a new step.


"""

from transformers import pipeline

# Load a more capable text2text-generation model
generator_structured = pipeline(
    "text2text-generation",
    model="google/flan-t5-base"
)

# Define the input prompt for structured output with a few-shot example
prompt_structured = (
    "Question: Extract the company name, founding year, founders, mission, and products/services from the text and present them as key-value pairs separated by semicolons. "
    "Example Text: 'Apple was founded in 1976 by Steve Jobs and Steve Wozniak. Its mission is to design, develop, and sell consumer electronics, computer software, and online services. Apple offers products like iPhone, Mac, Apple Watch, and services like Apple Music, iCloud.' "
    "Example Answer: Company Name: Apple; Founding Year: 1976; Founders: Steve Jobs, Steve Wozniak; Mission: design, develop, and sell consumer electronics, computer software, and online services; Products/Services: iPhone, Mac, Apple Watch, Apple Music, iCloud. "
    "Text: 'Google was founded in 1998 by Larry Page and Sergey Brin. The company's mission is to organize the world's information and make it universally accessible and useful. Google offers a wide range of products and services, including search engine, online advertising, cloud computing, software, and hardware.' "
    "Answer:"
)

# Generate text with structured output
result_structured = generator_structured(prompt_structured, max_new_tokens=200)

# Print the raw generated text
print("AI generated structured text:")
print(result_structured[0]['generated_text'])

"""**Reasoning**:
The `flan-t5-base` model successfully generated a structured string with key-value pairs separated by semicolons. Now, I need to parse this string into a Python dictionary, and then convert it into a Pandas DataFrame to display it as a table, which is the ultimate goal of the task.


"""

import pandas as pd

# Get the generated structured text
generated_text = result_structured[0]['generated_text']

# Initialize a dictionary to store the extracted data
extracted_data = {}

# Split the generated text by semicolon to get individual key-value pairs
pairs = generated_text.split(';')

for pair in pairs:
    if ':' in pair:
        key, value = pair.split(':', 1) # Split only on the first colon
        # Clean up keys and values
        clean_key = key.replace("Google's ", "").strip().replace(" ", "_").lower() # Remove 'Google's', strip, replace spaces with underscores, lowercase
        clean_value = value.strip()
        if clean_key == "founding_team": # Adjust key name to match 'founders' as in prompt
            clean_key = "founders"
        extracted_data[clean_key] = [clean_value] # Wrap in a list for DataFrame constructor

# Convert the dictionary to a Pandas DataFrame
df = pd.DataFrame(extracted_data)

# Display the DataFrame
print("Generated Summary Table:")
display(df)

"""**Reasoning**:
The previous code block failed to generate a DataFrame because the parsing logic was incorrect for the model's output format. The model used 'is' or 'are' as separators for key-value pairs, not colons. I will modify the parsing logic to correctly extract keys and values based on 'is' or 'are' separators, then clean them and construct the DataFrame.


"""

import pandas as pd

# Get the generated structured text
generated_text = result_structured[0]['generated_text']

# Initialize a dictionary to store the extracted data
extracted_data = {}

# Split the generated text by semicolon to get individual key-value pairs
pairs = generated_text.split(';')

for pair in pairs:
    pair = pair.strip() # Clean leading/trailing whitespace from the pair

    # Try to split by ' is ' or ' are ' as these are the separators used by the model
    split_found = False
    if ' is ' in pair:
        key, value = pair.split(' is ', 1)
        split_found = True
    elif ' are ' in pair:
        key, value = pair.split(' are ', 1)
        split_found = True

    if split_found:
        # Clean up keys and values
        clean_key = key.replace("Google's ", "").strip().replace(" ", "_").lower() # Remove 'Google's', strip, replace spaces with underscores, lowercase
        clean_value = value.strip()

        # Adjust key names to match the prompt's requested fields
        if clean_key == "founding_team":
            clean_key = "founders"
        elif clean_key == "products/services": # Handle the '/' in products/services
            clean_key = "products_services"

        extracted_data[clean_key] = [clean_value] # Wrap in a list for DataFrame constructor

# Convert the dictionary to a Pandas DataFrame
df = pd.DataFrame(extracted_data)

# Display the DataFrame
print("Generated Summary Table:")
display(df)

"""## Final Task

### Subtask:
Summarize the approach used for generating table-like output and present the final result to the user.

## Summary:

### Data Analysis Key Findings

*   **Model Selection Impact**: Initial attempts with `google/flan-t5-small` failed to produce structured output, instead echoing the input or returning minimal information. Switching to the larger `google/flan-t5-base` model was crucial for successfully generating structured text from the input prompt.
*   **Structured Output Generation**: The `google/flan-t5-base` model successfully extracted key information such as founding year, founders, mission, and products/services into a structured string format, albeit using " is " or " are " as separators instead of the initially anticipated colons and semicolons.
*   **Parsing Adaptability**: The parsing logic was successfully adapted to handle the `flan-t5-base` model's output format, correctly splitting key-value pairs based on " is " or " are ".
*   **Data Cleaning and Transformation**: Extracted keys were cleaned by removing prefixes like "Google's ", converting them to snake\_case, and standardizing specific key names (e.g., "founding\_team" to "founders", "products/services" to "products\_services").
*   **Final Table Output**: The cleaned and parsed data was successfully transformed into a Pandas DataFrame, presenting the summary information about Google in a clear tabular format.

### Insights or Next Steps

*   When generating structured output with `transformers` models, consider starting with more capable models or iteratively upgrading if initial attempts with smaller models yield unsatisfactory results, as model size significantly impacts performance for complex information extraction.
*   Always anticipate potential variations in the output format from language models and implement robust, adaptable parsing logic rather than relying solely on predefined separators.
"""