# -*- coding: utf-8 -*-
"""Text Similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKBqXEDF0ezMruIjC9zz2Pbby4NSmrs7
"""

from sentence_transformers import SentenceTransformer,util
#load the model
model=SentenceTransformer('all-MiniLM-L6-v2')
#take input from user
text1=input("enter text1:")
text2=input("enter text2:")
#convert the text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\nsimilarity score:",round(similarity.item(), 2))
if similarity>0.75:
  print("similarity level:high")
elif similarity>0.4:
  print("similarity level:medium")
else:
  print("similarity level:low")